### ISSUE TITLE
Yeoman Generator

### ISSUE THREAD

**Issue by desmondmorris** [hubot-scripts/packages#10]
Hi, I realize that this may be a misuse of this queue, but I figured it is the most appropriate place.  I wrote a (yeoman generator)[https://npmjs.org/package/generator-hubot-script] for creating hubot scripts.  The generated code is based on the [hubot-example](http://github.com/hubot-scripts/hubot-example) repo.

I think it could be a useful tool for folks.  Fork-worthy?  Either way, I wanted to put it on radar.

NPM:
https://npmjs.org/package/generator-hubot-script

REPO:
https://github.com/desmondmorris/generator-hubot-script

**Comment by technicalpickles** [comment]
I ended up starting a separate generator for this. I talk a bit more about it in https://github.com/github/hubot/pull/764 . The package is github.com/github/generator-hubot
