### ISSUE TITLE
hubot-currency

### ISSUE THREAD

**Issue by mihai** [hubot-scripts/packages#100]
Convert between currencies at daily exchange rates using Google's currency converter.

npm: https://www.npmjs.org/package/hubot-currency
repo: https://github.com/mihai/hubot-currency

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
