### ISSUE TITLE
hubot-startupidea

### ISSUE THREAD

**Issue by an0nym0use** [hubot-scripts/packages#101]
Returns a great (not guaranteed) startup idea.

npm: https://www.npmjs.org/package/hubot-startupidea
git: https://github.com/an0nym0use/hubot-startupidea

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
