### ISSUE TITLE
Add hubot-dnsimple

### ISSUE THREAD

**Issue by weppos** [hubot-scripts/packages#102]
## Links

npm: https://www.npmjs.org/package/hubot-dnsimple
repo: https://github.com/aetrion/hubot-dnsimple

## Description

A hubot script that checks domain availability via DNSimple.

---

Note: This script effectively replaces [`github/hubot-scripts/../dnsimple.coffee`](https://github.com/github/hubot-scripts/blob/master/src/scripts/dnsimple.coffee). I will provide a PR to the `github/hubot-scripts` repo as soon as this is accepted.

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.

**Comment by technicalpickles** [comment]
>  I will provide a PR to the github/hubot-scripts repo as soon as this is accepted.

Happy to review and merge that now :+1:
