### ISSUE TITLE
hubot-github-create-pullrequests

### ISSUE THREAD

**Issue by summera** [hubot-scripts/packages#103]
# Links
npm: https://www.npmjs.org/package/hubot-github-create-pullrequests
github: https://github.com/summera/hubot-github-create-pullrequests

# Description
A hubot script for creating pull requests

Cheers :)

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
