### ISSUE TITLE
hubot-in-space

### ISSUE THREAD

**Issue by frankiethekneeman** [hubot-scripts/packages#104]
A hubot extension to keep track of all the brave humans who have launched themselves into the final frontier.

GitHub: https://github.com/frankiethekneeman/hubot-in-space

Already available on NPM: https://www.npmjs.org/package/hubot-in-space

Based on the information available at http://www.howmanypeopleareinspacerightnow.com/

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
