### ISSUE TITLE
hubot-mondaypunday

### ISSUE THREAD

**Issue by wilfon** [hubot-scripts/packages#105]
start your week off with a brain warmup. or destroy all productivity by digging through the archives using the random function. 
grabs the monday punday image and link.

https://github.com/wilfon/hubot-mondaypunday

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
