### ISSUE TITLE
hubot-stash-poll

### ISSUE THREAD

**Issue by cskeppstedt** [hubot-scripts/packages#106]
Channel notifications when a pull request is opened in an Atlassian Stash repo.

*Why:* there are no webhooks for pull requests in Stash at this point, you need to poll.

**Source:** https://github.com/klarna/hubot-stash-poll
**Npm:** https://www.npmjs.org/package/hubot-stash-poll

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
