### ISSUE TITLE
hubot-nintendo

### ISSUE THREAD

**Issue by charly-palencia** [hubot-scripts/packages#108]
github: https://github.com/charly-palencia/hubot-nintendo

npm: https://www.npmjs.com/package/hubot-nintendo

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
