### ISSUE TITLE
hubot-sentiment

### ISSUE THREAD

**Issue by michikono** [hubot-scripts/packages#109]
Analyzes sentiment of any channels its in.

https://github.com/michikono/hubot-sentiment

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
