### ISSUE TITLE
hubot-jira

### ISSUE THREAD

**Issue by rustedgrail** [hubot-scripts/packages#110]
Update to the jira plugin from the old hubot-scripts repo, adding the ability to move jira issues.

https://github.com/rustedgrail/hubot-jira

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
