### ISSUE TITLE
hubot-giphy-gifme

### ISSUE THREAD

**Issue by bencentra** [hubot-scripts/packages#112]
Adds a "gif me" command for grabbing a random gif using the Giphy API. Can add a list of tags to refine your search, and set the "SFW guard" to prevent NSFW gifs popping up in company chat rooms.

https://github.com/bencentra/hubot-giphy-gifme
https://www.npmjs.com/package/hubot-giphy-gifme

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
