### ISSUE TITLE
hubot-github-comment-notifier

### ISSUE THREAD

**Issue by yujiosaka** [hubot-scripts/packages#113]
A GitHub pull request and issue comment notifier for hubot

`hubot-github-comment-notifier` makes the following assumptions:
- Pull request and issue comments should be notified with mentions when specified
- Pull request and issue comments may be notified in different rooms
- Other GitHub events than pull request and issue comment should be supported in other modules
- Only sends notifications when
  - pull request
    - pull request is (re)opened
    - comment is added to pull request
    - pull request is closed
  - issue
    - issue is (re)opened
    - comment is added to issue
    - issue is closed

https://github.com/yujiosaka/hubot-github-comment-notifier

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
