### ISSUE TITLE
hubot-clj

### ISSUE THREAD

**Issue by brbcoding** [hubot-scripts/packages#114]
Packaged the original [clj script](https://github.com/github/hubot-scripts/blob/master/src/scripts/clojure.coffee) for NPM.

Evaluates 1 line of clj using tryclj.com

https://github.com/brbcoding/hubot-clj

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
