### ISSUE TITLE
hubot-javascript

### ISSUE THREAD

**Issue by brbcoding** [hubot-scripts/packages#115]
Packaged the original [javascript sandbox script](https://github.com/github/hubot-scripts/blob/master/src/scripts/javascript-sandbox.coffee) for NPM.

Evaluates a line of JavaScript in a sandboxed environment

https://github.com/brbcoding/hubot-javascript

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
