### ISSUE TITLE
hubot-steal

### ISSUE THREAD

**Issue by brbcoding** [hubot-scripts/packages#116]
Shows an "animals stealing stuff" gif on `!steal`

https://github.com/brbcoding/hubot-steal

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
