### ISSUE TITLE
hubot-insulter

### ISSUE THREAD

**Issue by altryne** [hubot-scripts/packages#118]
https://github.com/altryne/hubot-insulter

This script randomly insults or compliments a user for you

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
