### ISSUE TITLE
hubot-flirt

### ISSUE THREAD

**Issue by jk-5** [hubot-scripts/packages#120]
Adds the 'hubot flirth with user' command to display a random flirt message

https://github.com/jk-5/hubot-flirt
https://www.npmjs.com/package/hubot-flirt

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
