### ISSUE TITLE
hubot-youtube-info

### ISSUE THREAD

**Issue by andreicek** [hubot-scripts/packages#121]
Ported the old youtube-info script with the last update.

Please see if everything fits.

 https://github.com/andreicek/hubot-youtube-info

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
