### ISSUE TITLE
hubot-spotify-search

### ISSUE THREAD

**Issue by kiequoo** [hubot-scripts/packages#122]
Hi, I created a script to search spotify, please check it out at https://github.com/kiequoo/hubot-spotify-search

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
