### ISSUE TITLE
bradys-balls

### ISSUE THREAD

**Issue by mikestecker** [hubot-scripts/packages#123]
Hi, I created a funny script with quotes from Tom Brady's press conference about 'balls', please check it out at https://github.com/mikestecker/bradys-balls

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
