### ISSUE TITLE
hubot-circleci-notify

### ISSUE THREAD

**Issue by jacobaweiss** [hubot-scripts/packages#124]
Here's a script to get notifications when builds complete on CircleCI for a given repo & branch or build id.

[https://github.com/IndieGoGo/hubot-circleci-notify](https://github.com/IndieGoGo/hubot-circleci-notify)

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
