### ISSUE TITLE
hubot-schedule

### ISSUE THREAD

**Issue by matsukaz** [hubot-scripts/packages#125]
Hi, I've created a message scheduler called 'hubot-schedule'.
It allows you to schedule a message in both cron-style and datetime-based format pattern.
Please check my repository.

https://github.com/matsukaz/hubot-schedule

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
