### ISSUE TITLE
hubot-untappd-friends

### ISSUE THREAD

**Issue by stephenyeargin** [hubot-scripts/packages#126]
- Project: https://github.com/stephenyeargin/hubot-untappd-friends
- Node Package: https://www.npmjs.com/package/hubot-untappd-friends
- Tested (and in active use) with IRC and Slack adapters

---

Command set:

```
    hubot untappd - Recent friend activity
    hubot untappd user <query> - Get stats about a particular user
    hubot untappd beer <query> - Get data about a particular beer
    hubot untappd brewery <query> - Get data about a particular brewery
    hubot untappd register - Instructions to register with the bot
    hubot untappd approve - Approve all pending friend requests
    hubot untappd friends - List the bot's friends
```

Configuration:

```
    export UNTAPPD_API_KEY=<Your Untappd API Key>
    export UNTAPPD_API_SECRET=<Your Untappd API Secret>
    export UNATPPD_API_ACCESS_TOKEN=<A valid OAuth 2 token>
````

---

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
