### ISSUE TITLE
hubot-daily-update

### ISSUE THREAD

**Issue by trodrigues** [hubot-scripts/packages#127]
Allows teams to store and read daily status updates

github: https://github.com/trodrigues/hubot-daily-update
npm: https://www.npmjs.com/package/hubot-daily-update

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
