### ISSUE TITLE
hubot twitter mention script

### ISSUE THREAD

**Issue by estiens** [hubot-scripts/packages#129]
https://github.com/estiens/hubot-twitter-mention-v2

https://www.npmjs.com/package/hubot-twitter-mentionv2

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
