### ISSUE TITLE
Reminder script with friendlier syntax

### ISSUE THREAD

**Issue by mx4492** [hubot-scripts/packages#130]
<https://github.com/mx4492/hubot-remind-her>

Quoting from the README
> - Supports both relative ("in 5 minutes") and absolute ("tomorrow 5 pm") time specification.
> - The syntax of the bot command is relaxed. It simply DWYM (Does what you mean) without expecting much grammar.
> - The confirmation given by the script uses a relative date instead of a scary complete ISOish date string.

Examples:

```
> hubot remind me in 10 minutes to have fun
> hubot remind me tomorrow 10 PM to eat
> hubot remind me at 18 Feb to be alive
```

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
