### ISSUE TITLE
hubot-strawpoll

### ISSUE THREAD

**Issue by ericsaupe** [hubot-scripts/packages#132]
https://github.com/ericsaupe/hubot-strawpoll
https://www.npmjs.com/package/hubot-strawpoll

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.

**Comment by ericsaupe** [comment]
:+1: Thanks
