### ISSUE TITLE
hubot-swanson

### ISSUE THREAD

**Issue by jamesseanwright** [hubot-scripts/packages#133]
A plugin for retrieving [Ron Swanson](http://en.wikipedia.org/wiki/Ron_Swanson) quotes from a web API I wrote:

https://github.com/jamesseanwright/hubot-swanson
https://www.npmjs.com/package/hubot-swanson

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
