### ISSUE TITLE
hubot-pingdom-tools

### ISSUE THREAD

**Issue by xurizaemon** [hubot-scripts/packages#134]
* [Hubot Pingdom Tools](https://github.com/xurizaemon/hubot-pingdom-tools)

This is similar but not the same as the old Hubot Pingdom script. That one uses authenticated API, where this one basically scrapes a public API endpoint. So I didn't submit this as a PR to existing Pingdom.

Currently this script returns a brief full page report of page load results and URL for more info via http://tools.pingdom.com/fpt

This is my first attempt at contribution to hubot-scripts, I've written a handful of internal-use only scripts also so I'm pretty new to it. I would be really grateful for your feedback / constructive criticism and to take that onboard before this gets published.

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
