### ISSUE TITLE
hubot-trello-organization

### ISSUE THREAD

**Issue by mohlendo** [hubot-scripts/packages#135]
The [hubot-trello-organization](https://github.com/mohlendo/hubot-trello-organization) script is for managing the boards of your organization with hubot. Is is different to the original trello script, that you don't specify one board but instead configure it for every room. The script also tries to automatically determine the board if the room name matches the board name.

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
