### ISSUE TITLE
https://github.com/kingbin/hubot-philipshue

### ISSUE THREAD

**Issue by kingbin** [hubot-scripts/packages#136]
cause I like my hue lights to twinkle when I hubot.

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
