### ISSUE TITLE
Disable liberal access to third-party apps?

### ISSUE THREAD

**Issue by patcon** [hubot-scripts/packages#138]
Hey @technicalpickles, might if I click this big button and lock this stuff down? I'd hate for my risk to become yours (I'm admittedly pretty conservative with account access).

https://imgur.com/g1okN7a

**Comment by technicalpickles** [comment]
@patcon sounds good. we don't have any private repos, so the risk is a bit less but it's a good precaution.

**Comment by patcon** [comment]
Yeah, but I if I understood it correctly, a malicious app that I irresponsibly auth'd at any point in my "github career" could have pushed malicious commits to any hubot script, right?

**Comment by technicalpickles** [comment]
This is done.
