### ISSUE TITLE
hubot-reddit

### ISSUE THREAD

**Issue by pablasso** [hubot-scripts/packages#139]
https://github.com/pablasso/hubot-reddit

This is a Reddit integration with Hubot. It retrieves the last N messages of a given subreddit.

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
