### ISSUE TITLE
hubot-oncall

### ISSUE THREAD

**Issue by pablasso** [hubot-scripts/packages#140]
This project tells you who is oncall on the current week and automatically rotates given a defined roster.

https://github.com/pablasso/hubot-oncall

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
