### ISSUE TITLE
hubot-4chan

### ISSUE THREAD

**Issue by pablasso** [hubot-scripts/packages#141]
4chan integration with Hubot.

https://github.com/pablasso/hubot-4chan

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
