### ISSUE TITLE
hubot-rate-limiter

### ISSUE THREAD

**Issue by shaundon** [hubot-scripts/packages#142]
Allows you to run commands with a rate limit, so that potentially annoying scripts aren't run too often.

Package: https://www.npmjs.org/package/hubot-rate-limiter
Repo: https://github.com/shaundon/hubot-rate-limiter

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
