### ISSUE TITLE
hubot-the-greater-good

### ISSUE THREAD

**Issue by shaundon** [hubot-scripts/packages#143]
Github: https://github.com/shaundon/hubot-the-greater-good
NPM: https://www.npmjs.com/package/hubot-the-greater-good

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.

After all, It's for the Greater Good (the greater good).

![](http://i.imgur.com/uT5DqJ3.gif)
