### ISSUE TITLE
hubot-minions

### ISSUE THREAD

**Issue by sahilsk** [hubot-scripts/packages#147]
Despicable minions images on demand

![alt random](http://sahilsk.github.io/hubot-minions/public/images/minions/Dancing-minion-icon.png)

https://github.com/sahilsk/hubot-minions

http://sahilsk.github.io/hubot-minions/

`npm install hubot-minions`

**Comment by technicalpickles** [comment]
This repository is deprecated, so no need to file issues and get repositories forked here: https://github.com/hubot-scripts/packages/issues/60

**Comment by sahilsk** [comment]
you know what it's confusing . You have so many links here and there each saying do it like this and do it like that.

I followed this : https://github.com/github/hubot-scripts/issues/1113

**Comment by sahilsk** [comment]
chuck it. My package is not so great to bear this headache of finding instructions to submit it.

Have a good day Sir.
