### ISSUE TITLE
Add status script (extracted from community repo)

### ISSUE THREAD

**Issue by patcon** [hubot-scripts/packages#22]
Repo: https://github.com/myplanetdigital/hubot-status
NPM: https://npmjs.org/package/hubot-status

<3

cc: @robertfwest @mattsjohnston

EDIT: Hey @mattsjohnston, I added you as a collab, but let me know if you need npmjs access too! (I'll need your username there :)

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
