### ISSUE TITLE
Add hubot-thecat

### ISSUE THREAD

**Issue by tenten0213** [hubot-scripts/packages#38]
source: https://github.com/tenten0213/hubot-thecat
npm: https://www.npmjs.org/package/hubot-thecat

Thanks!

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
