### ISSUE TITLE
hubot-quote-database

### ISSUE THREAD

**Issue by johnwyles** [hubot-scripts/packages#51]
Repo URL: https://github.com/johnwyles/hubot-quote-database
NPM: https://www.npmjs.org/package/hubot-quote-database

Thanks!

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
