### ISSUE TITLE
hubot-quote-grab

### ISSUE THREAD

**Issue by jjasghar** [hubot-scripts/packages#54]
This script is the ability to quote people in the different channels. This script is forked @jmacadam and does the majority of the work. I created a npm package for it and fixed up some minor bugs. 

package: https://npmjs.org/package/hubot-quote-grab

repo: https://github.com/jjasghar/hubot-quote-grab

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
