### ISSUE TITLE
Reconsider how this repository (and organization) are managed

### ISSUE THREAD

**Issue by technicalpickles** [hubot-scripts/packages#60]
There's a few problems with how things work right now:

* giving feedback on packages is difficult, because without a pull request, it's hard to comment on specific lines of code
* forking a repository to this repos is bad for SEO (ew), because the original repository shows up first
* once a repository is forked, now there are two places to update code, track issues and pul reuqests
* the acts of creating the fork, creating a team, adding the contributor, and posting back that you did that thing is suppppper tedious. It gets annoying basically after the first time.
* the hubot script catalog still doesn't include packages from here https://github.com/Aupajo/hubot-script-catalog/issues/7

I'm happy to hear suggestions to address any and all of these :grin: 

cc @therealklanni @jjasghar @patcon

**Comment by technicalpickles** [comment]
I had another idea that doesn't involve doing any work on a website (although will still want to do that at some point).

Basically, since we've been doing script packages, the example (or generated) package.json has the 'hubot-scripts' keyword. I already said that in the context of having a web accessible view. But it turns out, npm has a CLI way of searching packages, as well as seeing more info:

```
connor:examplebot technicalpickles$ npm search hubot-scripts pagerduty
NAME                   DESCRIPTION                                               AUTHOR            DATE       VERSION KEYWORDS                            
hubot-pager-me         PagerDuty integration for Hubot                           =technicalpickles 2014-12-16 2.0.2   hubot hubot-scripts pagerduty       
hubot-pagerduty-github PagerDuty Integration for checking who's on call, making… =patcon           2014-04-24 0.1.0   hubot hubot-scripts pagerduty alerts
npm home hubot-pager-me
```

At that point, npm opens a browser window  for the homepage, where the user can figure out the next steps for installing.

We can add that to the hubot docs, along with things like how to update hubot and scripts.

**Comment by afeld** [comment]
:heart: for a minimum viable solution that requires zero new code.

**Comment by patcon** [comment]
Great idea!

But perhaps most important, what happened to "connor" and why do you have his laptop?

**Comment by pablasso** [comment]
This organization shouldn't be needed really. +1 on adding to the docs how to search properly through npm.

**Comment by technicalpickles** [comment]
@bkeepers added documentation over in https://github.com/github/hubot/issues/956 so we are good on that front.

Here is my current plan:

* close this issue
* go through and close existing package requests on this repo with an explanation and link back to this issue
* file an issue to figure out what to do with all the packages that are already on this org
