### ISSUE TITLE
Magnum CI Notification Hook

### ISSUE THREAD

**Issue by wiebersk** [hubot-scripts/packages#82]
Hey guys - 

I created a basic plugin to have a listener for a Magnum-ci webhook and post a build notification to a set of rooms.  Could this be added to the listing of scripts?  

https://github.com/wiebersk/hubot-magnum-ci

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
