### ISSUE TITLE
hubot-http-code

### ISSUE THREAD

**Issue by Ajnasz** [hubot-scripts/packages#86]
Script to find information about http status codes.
Similar to hubot-http-status but it displays the short name and description in respond not only a link to wikipedia.

https://github.com/Ajnasz/hubot-http-code
https://www.npmjs.org/package/hubot-http-code

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
