### ISSUE TITLE
hubot-pugsofwesteros

### ISSUE THREAD

**Issue by shulance** [hubot-scripts/packages#89]
A hubot script to post a gif from [The Pugs of Westeros](https://www.youtube.com/watch?v=2EoQCtPR2-I) when someone mentions Game of Thrones, because we all how much hubot LOVES pugs!

npm: https://www.npmjs.org/package/hubot-pugsofwesteros
git: https://github.com/shulance/hubot-pugsofwesteros

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
