### ISSUE TITLE
hubot-introduce

### ISSUE THREAD

**Issue by webjay** [hubot-scripts/packages#90]
GitHub: https://github.com/webjay/hubot-introduce

npm: https://www.npmjs.org/package/hubot-introduce

    npm install hubot-introduce --save

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
