### ISSUE TITLE
hubot-karma-classic

### ISSUE THREAD

**Issue by notpeter** [hubot-scripts/packages#93]
So I know someone considered the karma.coffee deprecated and replaced by hubot-plusplus, but plusplus didn't work for us, so I just forked the original karma.coffee into a new package.

Had to rename it hubot-karma-classic because someone else already had an npm package as hubot-karma.

https://github.com/notpeter/hubot-karma-classic

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
