### ISSUE TITLE
hubot-semaphoreapp

### ISSUE THREAD

**Issue by ben** [hubot-scripts/packages#94]
https://github.com/ben/hubot-semaphoreapp

This supersedes [semaphoreapp.coffee](https://github.com/github/hubot-scripts/blob/master/src/scripts/semaphoreapp.coffee) and [Gridium/hubot-semaphore-deploy](https://github.com/Gridium/hubot-semaphore-deploy).

/cc @exalted

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
