### ISSUE TITLE
hubot-nietzche

### ISSUE THREAD

**Issue by clouseauu** [hubot-scripts/packages#99]
A hubot plugin to produce a random Nietzche quote whenever you feel a rush of existentialism

Github: https://github.com/clouseauu/hubot-nietzche
npm: https://www.npmjs.org/package/hubot-nietzche

**Comment by technicalpickles** [comment]
After discussion in https://github.com/hubot-scripts/packages/issues/60 we've decided to deprecate this organization. This shouldn't affect your package in any way, as you've already pushed the code up and have it on NPM. For users, they should be able to find it through NPM using `npm search hubot-scripts <query>`.
